/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v4.0
processor: MK64FN1M0xxx12
package_id: MK64FN1M0VMD12
mcu_data: ksdk2_0
processor_version: 3.0.1
pin_labels:
- {pin_num: A1, pin_signal: PTD7/CMT_IRO/UART0_TX/FTM0_CH7/FTM0_FLT1/SPI1_SIN, label: SPI1_MISO, identifier: SPI1_MISO}
- {pin_num: J5, pin_signal: PTA0/UART0_CTS_b/UART0_COL_b/FTM0_CH5/JTAG_TCLK/SWD_CLK/EZP_CLK, label: SWD_CLK, identifier: SWDCLK}
- {pin_num: J6, pin_signal: PTA1/UART0_RX/FTM0_CH6/JTAG_TDI/EZP_DI, label: AIR_WAKEN, identifier: AIR_WAKEN}
- {pin_num: K6, pin_signal: PTA2/UART0_TX/FTM0_CH7/JTAG_TDO/TRACE_SWO/EZP_DO, label: TOUCH_RST, identifier: TOUCH_RST}
- {pin_num: K7, pin_signal: PTA3/UART0_RTS_b/FTM0_CH0/JTAG_TMS/SWD_DIO, label: K64_SWDIO, identifier: K64_SWDIO}
- {pin_num: L7, pin_signal: PTA4/LLWU_P3/FTM0_CH1/NMI_b/EZP_CS_b, label: USER_SW1, identifier: USER_SW1}
- {pin_num: M8, pin_signal: PTA5/USB_CLKIN/FTM0_CH2/RMII0_RXER/MII0_RXER/CMP2_OUT/I2S0_TX_BCLK/JTAG_TRST_b, label: I2S_TX_BCLK, identifier: I2S_TX_BCLK}
- {pin_num: J7, pin_signal: PTA6/FTM0_CH3/CLKOUT/TRACE_CLKOUT, label: AIR_RESETN, identifier: AIR_RESETN}
- {pin_num: J8, pin_signal: ADC0_SE10/PTA7/FTM0_CH4/TRACE_D3, label: AIR_QUALITY_EN, identifier: AIR_QUALITY_EN}
- {pin_num: K8, pin_signal: ADC0_SE11/PTA8/FTM1_CH0/FTM1_QD_PHA/TRACE_D2, label: BUZZER_PWM, identifier: BUZZER_PWM}
- {pin_num: M9, pin_signal: PTA10/FTM2_CH0/MII0_RXD2/FTM2_QD_PHA/TRACE_D0, label: MB1_PWM, identifier: MB1_PWM}
- {pin_num: L9, pin_signal: PTA11/FTM2_CH1/MII0_RXCLK/I2C2_SDA/FTM2_QD_PHB, label: MB2_PWM, identifier: MB2_PWM}
- {pin_num: K9, pin_signal: CMP2_IN0/PTA12/CAN0_TX/FTM1_CH0/RMII0_RXD1/MII0_RXD1/I2C2_SCL/I2S0_TXD0/FTM1_QD_PHA, label: I2S_TXD, identifier: I2S_TXD}
- {pin_num: J9, pin_signal: CMP2_IN1/PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/RMII0_RXD0/MII0_RXD0/I2C2_SDA/I2S0_TX_FS/FTM1_QD_PHB, label: I2S_TX_FS;I2C2_SDA, identifier: I2S_TX_FS;I2C2_SDA}
- {pin_num: L10, pin_signal: PTA14/SPI0_PCS0/UART0_TX/RMII0_CRS_DV/MII0_RXDV/I2C2_SCL/I2S0_RX_BCLK/I2S0_TXD1, label: I2S_RX_BCLK;I2C2_SCL, identifier: I2S_RX_BCLK;I2C2_SCL}
- {pin_num: L11, pin_signal: PTA15/SPI0_SCK/UART0_RX/RMII0_TXEN/MII0_TXEN/I2S0_RXD0, label: I2S_RXD, identifier: I2S_RXD}
- {pin_num: K10, pin_signal: PTA16/SPI0_SOUT/UART0_CTS_b/UART0_COL_b/RMII0_TXD0/MII0_TXD0/I2S0_RX_FS/I2S0_RXD1, label: I2S_RX_FS, identifier: I2S_RX_FS}
- {pin_num: K11, pin_signal: ADC1_SE17/PTA17/SPI0_SIN/UART0_RTS_b/RMII0_TXD1/MII0_TXD1/I2S0_MCLK, label: I2S_MCLK, identifier: I2S_MCLK}
- {pin_num: M12, pin_signal: EXTAL0/PTA18/FTM0_FLT2/FTM_CLKIN0, label: K64_EXTAL, identifier: K64_EXTAL}
- {pin_num: M11, pin_signal: XTAL0/PTA19/FTM1_FLT0/FTM_CLKIN1/LPTMR0_ALT1, label: K64_XTAL, identifier: K64_XTAL}
- {pin_num: K12, pin_signal: PTA24/MII0_TXD2/FB_A29, label: TOUCH_TXEN, identifier: TOUCH_TXEN}
- {pin_num: J12, pin_signal: PTA25/MII0_TXCLK/FB_A28, label: AUTH_RST, identifier: AUTH_RST}
- {pin_num: J11, pin_signal: PTA26/MII0_TXD3/FB_A27, label: MB2_RST, identifier: MB2_RST}
- {pin_num: J10, pin_signal: PTA27/MII0_CRS/FB_A26, label: AIR_INTN, identifier: AIR_INTN}
- {pin_num: H12, pin_signal: PTA28/MII0_TXER/FB_A25, label: NTAG_FD, identifier: NTAG_FD}
- {pin_num: H11, pin_signal: PTA29/MII0_COL/FB_A24, label: CHG_STATE, identifier: CHG_STATE}
- {pin_num: H10, pin_signal: ADC0_SE8/ADC1_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/RMII0_MDIO/MII0_MDIO/FTM1_QD_PHA, label: KW41_WAKE_UP, identifier: KW41_WAKE_UP}
- {pin_num: H9, pin_signal: ADC0_SE9/ADC1_SE9/PTB1/I2C0_SDA/FTM1_CH1/RMII0_MDC/MII0_MDC/FTM1_QD_PHB, label: MB3_PWM, identifier: MB3_PWM}
- {pin_num: G12, pin_signal: ADC0_SE12/PTB2/I2C0_SCL/UART0_RTS_b/ENET0_1588_TMR0/FTM0_FLT3, label: I2C0_SCL, identifier: I2C0_SCL}
- {pin_num: G11, pin_signal: ADC0_SE13/PTB3/I2C0_SDA/UART0_CTS_b/UART0_COL_b/ENET0_1588_TMR1/FTM0_FLT0, label: I2C0_SDA, identifier: I2C0_SDA}
- {pin_num: G10, pin_signal: ADC1_SE10/PTB4/ENET0_1588_TMR2/FTM1_FLT0, label: MB1_INT, identifier: MB1_INT}
- {pin_num: F12, pin_signal: ADC1_SE12/PTB6/FB_AD23, label: MB3_AN, identifier: MB3_AN}
- {pin_num: F11, pin_signal: ADC1_SE13/PTB7/FB_AD22, label: MB3_INT, identifier: MB3_INT}
- {pin_num: F10, pin_signal: PTB8/UART3_RTS_b/FB_AD21, label: MB2_INT, identifier: MB2_INT}
- {pin_num: F9, pin_signal: PTB9/SPI1_PCS1/UART3_CTS_b/FB_AD20, label: SPI1_PCS1, identifier: SPI1_PCS1}
- {pin_num: E12, pin_signal: ADC1_SE14/PTB10/SPI1_PCS0/UART3_RX/FB_AD19/FTM0_FLT1, label: MB3_RST, identifier: MB3_RST}
- {pin_num: E11, pin_signal: ADC1_SE15/PTB11/SPI1_SCK/UART3_TX/FB_AD18/FTM0_FLT2, label: MB1_RST, identifier: MB1_RST}
- {pin_num: E10, pin_signal: PTB16/SPI1_SOUT/UART0_RX/FTM_CLKIN0/FB_AD17/EWM_IN, label: UART_DBG_RX, identifier: UART_DBG_RX}
- {pin_num: E9, pin_signal: PTB17/SPI1_SIN/UART0_TX/FTM_CLKIN1/FB_AD16/EWM_OUT_b, label: UART_DBG_TX, identifier: UART_DBG_TX}
- {pin_num: D12, pin_signal: PTB18/CAN0_TX/FTM2_CH0/I2S0_TX_BCLK/FB_AD15/FTM2_QD_PHA, label: CAN_TX, identifier: CAN_TX}
- {pin_num: D11, pin_signal: PTB19/CAN0_RX/FTM2_CH1/I2S0_TX_FS/FB_OE_b/FTM2_QD_PHB, label: CAN_RX, identifier: CAN_RX}
- {pin_num: D10, pin_signal: PTB20/SPI2_PCS0/FB_AD31/CMP0_OUT, label: DISP_SPI_CS, identifier: DISP_SPI_CS}
- {pin_num: C12, pin_signal: PTB22/SPI2_SOUT/FB_AD29/CMP2_OUT, label: DISP_SPI_SDI, identifier: DISP_SPI_SDI}
- {pin_num: C11, pin_signal: PTB23/SPI2_SIN/SPI0_PCS5/FB_AD28, label: KW41_RST, identifier: KW41_RST}
- {pin_num: B12, pin_signal: ADC0_SE14/PTC0/SPI0_PCS4/PDB0_EXTRG/USB_SOF_OUT/FB_AD14/I2S0_TXD1, label: AMB_INT, identifier: AMB_INT}
- {pin_num: B11, pin_signal: ADC0_SE15/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FB_AD13/I2S0_TXD0, label: ACCEL_INT1, identifier: ACCEL_INT1}
- {pin_num: A12, pin_signal: ADC0_SE4b/CMP1_IN0/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FB_AD12/I2S0_TX_FS, label: MB3_SPI_CS, identifier: MB3_SPI_CS}
- {pin_num: A11, pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT/I2S0_TX_BCLK, label: MB2_SPI_CS, identifier: MB2_SPI_CS}
- {pin_num: A9, pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/FB_AD11/CMP1_OUT, label: MB1_SPI_CS, identifier: MB1_SPI_CS}
- {pin_num: D8, pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/FB_AD10/CMP0_OUT/FTM0_CH2, label: MB_SPI_SCK, identifier: MB_SPI_SCK}
- {pin_num: C8, pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB0_EXTRG/I2S0_RX_BCLK/FB_AD9/I2S0_MCLK, label: MB_SPI_MOSI, identifier: MB_SPI_MOSI}
- {pin_num: B8, pin_signal: CMP0_IN1/PTC7/SPI0_SIN/USB_SOF_OUT/I2S0_RX_FS/FB_AD8, label: MB_SPI_MISO, identifier: MB_SPI_MISO}
- {pin_num: D7, pin_signal: ADC1_SE5b/CMP0_IN3/PTC9/FTM3_CH5/I2S0_RX_BCLK/FB_AD6/FTM2_FLT0, label: RGB_B, identifier: RGB_B}
- {pin_num: A8, pin_signal: ADC1_SE4b/CMP0_IN2/PTC8/FTM3_CH4/I2S0_MCLK/FB_AD7, label: RGB_R, identifier: RGB_R}
- {pin_num: C7, pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/I2S0_RX_FS/FB_AD5, label: I2C1_SCL, identifier: I2C1_SCL}
- {pin_num: B7, pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/I2S0_RXD1/FB_RW_b, label: I2C1_SDA, identifier: I2C1_SDA}
- {pin_num: A7, pin_signal: PTC12/UART4_RTS_b/FB_AD27/FTM3_FLT0, label: NTAG_EN, identifier: NTAG_EN}
- {pin_num: D6, pin_signal: PTC13/UART4_CTS_b/FB_AD26, label: KW41_PB18, identifier: KW41_PB18}
- {pin_num: C6, pin_signal: PTC14/UART4_RX/FB_AD25, label: BAT_SENS_EN, identifier: BAT_SENS_EN}
- {pin_num: B6, pin_signal: PTC15/UART4_TX/FB_AD24, label: GYRO_RST, identifier: GYRO_RST}
- {pin_num: A6, pin_signal: PTC16/UART3_RX/ENET0_1588_TMR0/FB_CS5_b/FB_TSIZ1/FB_BE23_16_BLS15_8_b, label: UART3_RX, identifier: UART3_RX}
- {pin_num: D5, pin_signal: PTC17/UART3_TX/ENET0_1588_TMR1/FB_CS4_b/FB_TSIZ0/FB_BE31_24_BLS7_0_b, label: UART3_TX, identifier: UART3_TX}
- {pin_num: C5, pin_signal: PTC18/UART3_RTS_b/ENET0_1588_TMR2/FB_TBST_b/FB_CS2_b/FB_BE15_8_BLS23_16_b, label: GYRO_INT2, identifier: GYRO_INT2}
- {pin_num: B5, pin_signal: PTC19/UART3_CTS_b/ENET0_1588_TMR3/FB_CS3_b/FB_BE7_0_BLS31_24_b/FB_TA_b, label: USB_VBUS, identifier: USB_VBUS}
- {pin_num: L12, pin_signal: RESET_b, label: K64_RST, identifier: K64_RST}
- {pin_num: A5, pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b, label: RTC_INT, identifier: RTC_INT}
- {pin_num: D4, pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FB_CS0_b, label: GYRO_INT1, identifier: GYRO_INT1}
- {pin_num: C4, pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FB_AD4/I2C0_SCL, label: UART2_RX, identifier: UART2_RX}
- {pin_num: B4, pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FB_AD3/I2C0_SDA, label: UART2_TX, identifier: UART2_TX}
- {pin_num: A4, pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FB_AD2/EWM_IN/SPI1_PCS0, label: SPI1_PCS0, identifier: SPI1_PCS0}
- {pin_num: A3, pin_signal: ADC0_SE6b/PTD5/SPI0_PCS2/UART0_CTS_b/UART0_COL_b/FTM0_CH5/FB_AD1/EWM_OUT_b/SPI1_SCK, label: SPI1_SCK, identifier: SPI1_SCK}
- {pin_num: A2, pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH6/FB_AD0/FTM0_FLT0/SPI1_SOUT, label: SPI1_MOSI, identifier: SPI1_MOSI}
- {pin_num: B9, pin_signal: PTD9/I2C0_SDA/UART5_TX/FB_A17, label: DISP_EN, identifier: DISP_EN}
- {pin_num: B3, pin_signal: PTD10/UART5_RTS_b/FB_A18, label: PRESSURE_INT2, identifier: PRESSURE_INT2}
- {pin_num: B2, pin_signal: PTD11/SPI2_PCS0/UART5_CTS_b/SDHC0_CLKIN/FB_A19, label: ACCEL_RST, identifier: ACCEL_RST}
- {pin_num: B1, pin_signal: PTD12/SPI2_SCK/FTM3_FLT0/SDHC0_D4/FB_A20, label: PRESSURE_INT1, identifier: PRESSURE_INT1}
- {pin_num: C3, pin_signal: PTD13/SPI2_SOUT/SDHC0_D5/FB_A21, label: ACCEL_INT2, identifier: ACCEL_INT2}
- {pin_num: C2, pin_signal: PTD14/SPI2_SIN/SDHC0_D6/FB_A22, label: RTC_CLKOE, identifier: RTC_CLKOE}
- {pin_num: C1, pin_signal: PTD15/SPI2_PCS1/SDHC0_D7/FB_A23, label: DISP_DISP, identifier: DISP_DISP}
- {pin_num: D3, pin_signal: ADC1_SE4a/PTE0/SPI1_PCS1/UART1_TX/SDHC0_D1/TRACE_CLKOUT/I2C1_SDA/RTC_CLKOUT, label: SD_D1, identifier: SD_D1}
- {pin_num: D2, pin_signal: ADC1_SE5a/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/SDHC0_D0/TRACE_D3/I2C1_SCL/SPI1_SIN, label: SD_D0, identifier: SD_D0}
- {pin_num: D1, pin_signal: ADC0_DP2/ADC1_SE6a/PTE2/LLWU_P1/SPI1_SCK/UART1_CTS_b/SDHC0_DCLK/TRACE_D2, label: SD_CLK, identifier: SD_CLK}
- {pin_num: E4, pin_signal: ADC0_DM2/ADC1_SE7a/PTE3/SPI1_SIN/UART1_RTS_b/SDHC0_CMD/TRACE_D1/SPI1_SOUT, label: SD_CMD, identifier: SD_CMD}
- {pin_num: E3, pin_signal: PTE4/LLWU_P2/SPI1_PCS0/UART3_TX/SDHC0_D3/TRACE_D0, label: SD_D3, identifier: SD_D3}
- {pin_num: E2, pin_signal: PTE5/SPI1_PCS2/UART3_RX/SDHC0_D2/FTM3_CH0, label: SD_D2, identifier: SD_D2}
- {pin_num: E1, pin_signal: PTE6/SPI1_PCS3/UART3_CTS_b/I2S0_MCLK/FTM3_CH1/USB_SOF_OUT, label: DISP_EXTCOMIN, identifier: DISP_EXTCOMIN}
- {pin_num: F4, pin_signal: PTE7/UART3_RTS_b/I2S0_RXD0/FTM3_CH2, label: RGB_G, identifier: RGB_G}
- {pin_num: F2, pin_signal: PTE9/I2S0_TXD1/UART5_RX/I2S0_RX_BCLK/FTM3_CH4, label: USER_SW2, identifier: USER_SW2}
- {pin_num: F1, pin_signal: PTE10/UART5_CTS_b/I2S0_TXD0/FTM3_CH5, label: USER_SW3, identifier: USER_SW3}
- {pin_num: G4, pin_signal: PTE11/UART5_RTS_b/I2S0_TX_FS/FTM3_CH6, label: DISP_EXTMODE, identifier: DISP_EXTMODE}
- {pin_num: G3, pin_signal: PTE12/I2S0_TX_BCLK/FTM3_CH7, label: DISP_BLIGHT, identifier: DISP_BLIGHT}
- {pin_num: M4, pin_signal: ADC0_SE17/PTE24/UART4_TX/I2C0_SCL/EWM_OUT_b, label: KW41_UART_RX, identifier: KW41_UART_RX}
- {pin_num: K5, pin_signal: ADC0_SE18/PTE25/UART4_RX/I2C0_SDA/EWM_IN, label: KW41_UART_TX, identifier: KW41_UART_TX}
- {pin_num: K4, pin_signal: PTE26/ENET_1588_CLKIN/UART4_CTS_b/RTC_CLKOUT/USB_CLKIN, label: KW41_UART_RTS, identifier: KW41_UART_RTS}
- {pin_num: J4, pin_signal: PTE27/UART4_RTS_b, label: KW41_UART_CTS, identifier: KW41_UART_CTS}
- {pin_num: H4, pin_signal: PTE28, label: USER_SW4, identifier: USER_SW4}
- {pin_num: H1, pin_signal: USB0_DP, label: USB_DP, identifier: USB_DP}
- {pin_num: H2, pin_signal: USB0_DM, label: USB_DM, identifier: USB_DM}
- {pin_num: J3, pin_signal: ADC0_SE16/CMP1_IN2/ADC0_SE21, label: BAT_SENS, identifier: BAT_SENS}
- {pin_num: K3, pin_signal: ADC1_SE16/CMP2_IN2/ADC0_SE22, label: MB1_AN, identifier: MB1_AN}
- {pin_num: L3, pin_signal: DAC0_OUT/CMP1_IN3/ADC0_SE23, label: MB2_AN, identifier: MB2_AN}
- {pin_num: M6, pin_signal: EXTAL32, label: K64_EXTAL32, identifier: K64_EXTAL32}
- {pin_num: D9, pin_signal: PTB21/SPI2_SCK/FB_AD30/CMP1_OUT, label: DISP_SPI_SCK, identifier: DISP_SPI_SCK}
- {pin_num: C9, pin_signal: PTD8/I2C0_SCL/UART5_RX/FB_A16, label: AIR_QUALITY_I2C_EN, identifier: AIR_QUALITY_I2C_EN}
- {pin_num: L8, pin_signal: PTA9/FTM1_CH1/MII0_RXD3/FTM1_QD_PHB/TRACE_D1, label: TOUCH_INT, identifier: TOUCH_INT}
- {pin_num: G9, pin_signal: ADC1_SE11/PTB5/ENET0_1588_TMR3/FTM2_FLT0, label: NTAG_I2C_EN, identifier: NTAG_I2C_EN}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
     BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: A1, peripheral: SPI1, signal: SIN, pin_signal: PTD7/CMT_IRO/UART0_TX/FTM0_CH7/FTM0_FLT1/SPI1_SIN, drive_strength: low}
  - {pin_num: J5, peripheral: JTAG, signal: JTAG_TCLK_SWD_CLK, pin_signal: PTA0/UART0_CTS_b/UART0_COL_b/FTM0_CH5/JTAG_TCLK/SWD_CLK/EZP_CLK}
  - {pin_num: J6, peripheral: GPIOA, signal: 'GPIO, 1', pin_signal: PTA1/UART0_RX/FTM0_CH6/JTAG_TDI/EZP_DI, direction: OUTPUT, open_drain: enable}
  - {pin_num: K6, peripheral: GPIOA, signal: 'GPIO, 2', pin_signal: PTA2/UART0_TX/FTM0_CH7/JTAG_TDO/TRACE_SWO/EZP_DO, direction: OUTPUT, open_drain: enable}
  - {pin_num: K7, peripheral: JTAG, signal: JTAG_TMS_SWD_DIO, pin_signal: PTA3/UART0_RTS_b/FTM0_CH0/JTAG_TMS/SWD_DIO}
  - {pin_num: L7, peripheral: GPIOA, signal: 'GPIO, 4', pin_signal: PTA4/LLWU_P3/FTM0_CH1/NMI_b/EZP_CS_b, direction: INPUT, pull_select: up, pull_enable: disable,
    passive_filter: enable}
  - {pin_num: M8, peripheral: I2S0, signal: TX_BCLK, pin_signal: PTA5/USB_CLKIN/FTM0_CH2/RMII0_RXER/MII0_RXER/CMP2_OUT/I2S0_TX_BCLK/JTAG_TRST_b}
  - {pin_num: J7, peripheral: GPIOA, signal: 'GPIO, 6', pin_signal: PTA6/FTM0_CH3/CLKOUT/TRACE_CLKOUT, direction: OUTPUT, open_drain: enable, drive_strength: high}
  - {pin_num: J8, peripheral: GPIOA, signal: 'GPIO, 7', pin_signal: ADC0_SE10/PTA7/FTM0_CH4/TRACE_D3, direction: OUTPUT, pull_select: down}
  - {pin_num: K8, peripheral: FTM1, signal: 'CH, 0', pin_signal: ADC0_SE11/PTA8/FTM1_CH0/FTM1_QD_PHA/TRACE_D2, direction: OUTPUT}
  - {pin_num: M9, peripheral: FTM2, signal: 'CH, 0', pin_signal: PTA10/FTM2_CH0/MII0_RXD2/FTM2_QD_PHA/TRACE_D0, direction: OUTPUT}
  - {pin_num: L9, peripheral: FTM2, signal: 'CH, 1', pin_signal: PTA11/FTM2_CH1/MII0_RXCLK/I2C2_SDA/FTM2_QD_PHB, direction: OUTPUT}
  - {pin_num: K9, peripheral: I2S0, signal: TXD0, pin_signal: CMP2_IN0/PTA12/CAN0_TX/FTM1_CH0/RMII0_RXD1/MII0_RXD1/I2C2_SCL/I2S0_TXD0/FTM1_QD_PHA}
  - {pin_num: J9, peripheral: I2C2, signal: SDA, pin_signal: CMP2_IN1/PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/RMII0_RXD0/MII0_RXD0/I2C2_SDA/I2S0_TX_FS/FTM1_QD_PHB, identifier: I2C2_SDA,
    open_drain: enable, drive_strength: high}
  - {pin_num: L10, peripheral: I2C2, signal: SCL, pin_signal: PTA14/SPI0_PCS0/UART0_TX/RMII0_CRS_DV/MII0_RXDV/I2C2_SCL/I2S0_RX_BCLK/I2S0_TXD1, identifier: I2C2_SCL,
    open_drain: enable, drive_strength: high}
  - {pin_num: L11, peripheral: I2S0, signal: RXD0, pin_signal: PTA15/SPI0_SCK/UART0_RX/RMII0_TXEN/MII0_TXEN/I2S0_RXD0}
  - {pin_num: K10, peripheral: I2S0, signal: RX_FS, pin_signal: PTA16/SPI0_SOUT/UART0_CTS_b/UART0_COL_b/RMII0_TXD0/MII0_TXD0/I2S0_RX_FS/I2S0_RXD1}
  - {pin_num: K11, peripheral: I2S0, signal: MCLK, pin_signal: ADC1_SE17/PTA17/SPI0_SIN/UART0_RTS_b/RMII0_TXD1/MII0_TXD1/I2S0_MCLK}
  - {pin_num: M12, peripheral: OSC, signal: EXTAL0, pin_signal: EXTAL0/PTA18/FTM0_FLT2/FTM_CLKIN0, identifier: ''}
  - {pin_num: M11, peripheral: OSC, signal: XTAL0, pin_signal: XTAL0/PTA19/FTM1_FLT0/FTM_CLKIN1/LPTMR0_ALT1}
  - {pin_num: K12, peripheral: GPIOA, signal: 'GPIO, 24', pin_signal: PTA24/MII0_TXD2/FB_A29, direction: OUTPUT, open_drain: enable}
  - {pin_num: J12, peripheral: GPIOA, signal: 'GPIO, 25', pin_signal: PTA25/MII0_TXCLK/FB_A28, direction: OUTPUT}
  - {pin_num: J11, peripheral: GPIOA, signal: 'GPIO, 26', pin_signal: PTA26/MII0_TXD3/FB_A27, direction: OUTPUT}
  - {pin_num: J10, peripheral: GPIOA, signal: 'GPIO, 27', pin_signal: PTA27/MII0_CRS/FB_A26, direction: INPUT}
  - {pin_num: H12, peripheral: GPIOA, signal: 'GPIO, 28', pin_signal: PTA28/MII0_TXER/FB_A25, direction: INPUT}
  - {pin_num: H11, peripheral: GPIOA, signal: 'GPIO, 29', pin_signal: PTA29/MII0_COL/FB_A24, direction: INPUT}
  - {pin_num: H10, peripheral: GPIOB, signal: 'GPIO, 0', pin_signal: ADC0_SE8/ADC1_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/RMII0_MDIO/MII0_MDIO/FTM1_QD_PHA, direction: OUTPUT}
  - {pin_num: H9, peripheral: FTM1, signal: 'CH, 1', pin_signal: ADC0_SE9/ADC1_SE9/PTB1/I2C0_SDA/FTM1_CH1/RMII0_MDC/MII0_MDC/FTM1_QD_PHB, direction: OUTPUT}
  - {pin_num: G12, peripheral: I2C0, signal: SCL, pin_signal: ADC0_SE12/PTB2/I2C0_SCL/UART0_RTS_b/ENET0_1588_TMR0/FTM0_FLT3, open_drain: enable, drive_strength: high}
  - {pin_num: G11, peripheral: I2C0, signal: SDA, pin_signal: ADC0_SE13/PTB3/I2C0_SDA/UART0_CTS_b/UART0_COL_b/ENET0_1588_TMR1/FTM0_FLT0, open_drain: enable, drive_strength: high}
  - {pin_num: G10, peripheral: GPIOB, signal: 'GPIO, 4', pin_signal: ADC1_SE10/PTB4/ENET0_1588_TMR2/FTM1_FLT0, direction: INPUT}
  - {pin_num: F12, peripheral: ADC1, signal: 'SE, 12', pin_signal: ADC1_SE12/PTB6/FB_AD23}
  - {pin_num: F11, peripheral: GPIOB, signal: 'GPIO, 7', pin_signal: ADC1_SE13/PTB7/FB_AD22, direction: INPUT}
  - {pin_num: F10, peripheral: GPIOB, signal: 'GPIO, 8', pin_signal: PTB8/UART3_RTS_b/FB_AD21, direction: INPUT}
  - {pin_num: F9, peripheral: SPI1, signal: PCS1, pin_signal: PTB9/SPI1_PCS1/UART3_CTS_b/FB_AD20}
  - {pin_num: E12, peripheral: GPIOB, signal: 'GPIO, 10', pin_signal: ADC1_SE14/PTB10/SPI1_PCS0/UART3_RX/FB_AD19/FTM0_FLT1, direction: OUTPUT}
  - {pin_num: E11, peripheral: GPIOB, signal: 'GPIO, 11', pin_signal: ADC1_SE15/PTB11/SPI1_SCK/UART3_TX/FB_AD18/FTM0_FLT2, direction: OUTPUT}
  - {pin_num: E10, peripheral: UART0, signal: RX, pin_signal: PTB16/SPI1_SOUT/UART0_RX/FTM_CLKIN0/FB_AD17/EWM_IN}
  - {pin_num: E9, peripheral: UART0, signal: TX, pin_signal: PTB17/SPI1_SIN/UART0_TX/FTM_CLKIN1/FB_AD16/EWM_OUT_b, direction: OUTPUT}
  - {pin_num: D12, peripheral: CAN0, signal: TX, pin_signal: PTB18/CAN0_TX/FTM2_CH0/I2S0_TX_BCLK/FB_AD15/FTM2_QD_PHA}
  - {pin_num: D11, peripheral: CAN0, signal: RX, pin_signal: PTB19/CAN0_RX/FTM2_CH1/I2S0_TX_FS/FB_OE_b/FTM2_QD_PHB}
  - {pin_num: C11, peripheral: GPIOB, signal: 'GPIO, 23', pin_signal: PTB23/SPI2_SIN/SPI0_PCS5/FB_AD28, direction: OUTPUT, open_drain: enable, drive_strength: high}
  - {pin_num: B12, peripheral: GPIOC, signal: 'GPIO, 0', pin_signal: ADC0_SE14/PTC0/SPI0_PCS4/PDB0_EXTRG/USB_SOF_OUT/FB_AD14/I2S0_TXD1, direction: INPUT}
  - {pin_num: B11, peripheral: GPIOC, signal: 'GPIO, 1', pin_signal: ADC0_SE15/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FB_AD13/I2S0_TXD0, direction: INPUT}
  - {pin_num: A12, peripheral: SPI0, signal: PCS2, pin_signal: ADC0_SE4b/CMP1_IN0/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FB_AD12/I2S0_TX_FS}
  - {pin_num: A11, peripheral: SPI0, signal: PCS1, pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT/I2S0_TX_BCLK}
  - {pin_num: A9, peripheral: SPI0, signal: PCS0_SS, pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/FB_AD11/CMP1_OUT, direction: OUTPUT}
  - {pin_num: D8, peripheral: SPI0, signal: SCK, pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/FB_AD10/CMP0_OUT/FTM0_CH2, direction: OUTPUT}
  - {pin_num: C8, peripheral: SPI0, signal: SOUT, pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB0_EXTRG/I2S0_RX_BCLK/FB_AD9/I2S0_MCLK}
  - {pin_num: B8, peripheral: SPI0, signal: SIN, pin_signal: CMP0_IN1/PTC7/SPI0_SIN/USB_SOF_OUT/I2S0_RX_FS/FB_AD8}
  - {pin_num: C7, peripheral: I2C1, signal: SCL, pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/I2S0_RX_FS/FB_AD5, open_drain: enable, drive_strength: high}
  - {pin_num: B7, peripheral: I2C1, signal: SDA, pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/I2S0_RXD1/FB_RW_b, open_drain: enable, drive_strength: high}
  - {pin_num: A7, peripheral: GPIOC, signal: 'GPIO, 12', pin_signal: PTC12/UART4_RTS_b/FB_AD27/FTM3_FLT0, direction: OUTPUT}
  - {pin_num: D6, peripheral: GPIOC, signal: 'GPIO, 13', pin_signal: PTC13/UART4_CTS_b/FB_AD26, direction: INPUT, open_drain: enable, drive_strength: high}
  - {pin_num: C6, peripheral: GPIOC, signal: 'GPIO, 14', pin_signal: PTC14/UART4_RX/FB_AD25, direction: OUTPUT}
  - {pin_num: B6, peripheral: GPIOC, signal: 'GPIO, 15', pin_signal: PTC15/UART4_TX/FB_AD24, direction: OUTPUT, open_drain: enable, drive_strength: high}
  - {pin_num: A6, peripheral: UART3, signal: RX, pin_signal: PTC16/UART3_RX/ENET0_1588_TMR0/FB_CS5_b/FB_TSIZ1/FB_BE23_16_BLS15_8_b}
  - {pin_num: D5, peripheral: UART3, signal: TX, pin_signal: PTC17/UART3_TX/ENET0_1588_TMR1/FB_CS4_b/FB_TSIZ0/FB_BE31_24_BLS7_0_b, direction: OUTPUT}
  - {pin_num: C5, peripheral: GPIOC, signal: 'GPIO, 18', pin_signal: PTC18/UART3_RTS_b/ENET0_1588_TMR2/FB_TBST_b/FB_CS2_b/FB_BE15_8_BLS23_16_b, direction: INPUT}
  - {pin_num: B5, peripheral: GPIOC, signal: 'GPIO, 19', pin_signal: PTC19/UART3_CTS_b/ENET0_1588_TMR3/FB_CS3_b/FB_BE7_0_BLS31_24_b/FB_TA_b, direction: INPUT}
  - {pin_num: L12, peripheral: RCM, signal: RESET, pin_signal: RESET_b}
  - {pin_num: A5, peripheral: GPIOD, signal: 'GPIO, 0', pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b, direction: INPUT, pull_select: up,
    pull_enable: enable}
  - {pin_num: D4, peripheral: GPIOD, signal: 'GPIO, 1', pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FB_CS0_b, direction: INPUT}
  - {pin_num: C4, peripheral: UART2, signal: RX, pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FB_AD4/I2C0_SCL}
  - {pin_num: B4, peripheral: UART2, signal: TX, pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FB_AD3/I2C0_SDA, direction: OUTPUT}
  - {pin_num: A4, peripheral: SPI1, signal: PCS0_SS, pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FB_AD2/EWM_IN/SPI1_PCS0, direction: OUTPUT, open_drain: enable,
    drive_strength: high}
  - {pin_num: A3, peripheral: SPI1, signal: SCK, pin_signal: ADC0_SE6b/PTD5/SPI0_PCS2/UART0_CTS_b/UART0_COL_b/FTM0_CH5/FB_AD1/EWM_OUT_b/SPI1_SCK, direction: OUTPUT}
  - {pin_num: A2, peripheral: SPI1, signal: SOUT, pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH6/FB_AD0/FTM0_FLT0/SPI1_SOUT}
  - {pin_num: B9, peripheral: GPIOD, signal: 'GPIO, 9', pin_signal: PTD9/I2C0_SDA/UART5_TX/FB_A17, direction: OUTPUT}
  - {pin_num: B3, peripheral: GPIOD, signal: 'GPIO, 10', pin_signal: PTD10/UART5_RTS_b/FB_A18, direction: INPUT}
  - {pin_num: B2, peripheral: GPIOD, signal: 'GPIO, 11', pin_signal: PTD11/SPI2_PCS0/UART5_CTS_b/SDHC0_CLKIN/FB_A19, direction: OUTPUT}
  - {pin_num: B1, peripheral: GPIOD, signal: 'GPIO, 12', pin_signal: PTD12/SPI2_SCK/FTM3_FLT0/SDHC0_D4/FB_A20, direction: INPUT}
  - {pin_num: C3, peripheral: GPIOD, signal: 'GPIO, 13', pin_signal: PTD13/SPI2_SOUT/SDHC0_D5/FB_A21, direction: INPUT}
  - {pin_num: C2, peripheral: GPIOD, signal: 'GPIO, 14', pin_signal: PTD14/SPI2_SIN/SDHC0_D6/FB_A22, direction: OUTPUT}
  - {pin_num: C1, peripheral: GPIOD, signal: 'GPIO, 15', pin_signal: PTD15/SPI2_PCS1/SDHC0_D7/FB_A23, direction: OUTPUT}
  - {pin_num: D3, peripheral: SDHC, signal: 'DATA, 1', pin_signal: ADC1_SE4a/PTE0/SPI1_PCS1/UART1_TX/SDHC0_D1/TRACE_CLKOUT/I2C1_SDA/RTC_CLKOUT}
  - {pin_num: D2, peripheral: SDHC, signal: 'DATA, 0', pin_signal: ADC1_SE5a/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/SDHC0_D0/TRACE_D3/I2C1_SCL/SPI1_SIN}
  - {pin_num: D1, peripheral: SDHC, signal: DCLK, pin_signal: ADC0_DP2/ADC1_SE6a/PTE2/LLWU_P1/SPI1_SCK/UART1_CTS_b/SDHC0_DCLK/TRACE_D2}
  - {pin_num: E4, peripheral: SDHC, signal: CMD, pin_signal: ADC0_DM2/ADC1_SE7a/PTE3/SPI1_SIN/UART1_RTS_b/SDHC0_CMD/TRACE_D1/SPI1_SOUT}
  - {pin_num: E3, peripheral: SDHC, signal: 'DATA, 3', pin_signal: PTE4/LLWU_P2/SPI1_PCS0/UART3_TX/SDHC0_D3/TRACE_D0}
  - {pin_num: E2, peripheral: SDHC, signal: 'DATA, 2', pin_signal: PTE5/SPI1_PCS2/UART3_RX/SDHC0_D2/FTM3_CH0}
  - {pin_num: E1, peripheral: FTM3, signal: 'CH, 1', pin_signal: PTE6/SPI1_PCS3/UART3_CTS_b/I2S0_MCLK/FTM3_CH1/USB_SOF_OUT, identifier: ''}
  - {pin_num: F2, peripheral: GPIOE, signal: 'GPIO, 9', pin_signal: PTE9/I2S0_TXD1/UART5_RX/I2S0_RX_BCLK/FTM3_CH4, direction: INPUT, passive_filter: enable}
  - {pin_num: F1, peripheral: GPIOE, signal: 'GPIO, 10', pin_signal: PTE10/UART5_CTS_b/I2S0_TXD0/FTM3_CH5, direction: INPUT, passive_filter: enable}
  - {pin_num: G4, peripheral: GPIOE, signal: 'GPIO, 11', pin_signal: PTE11/UART5_RTS_b/I2S0_TX_FS/FTM3_CH6, direction: OUTPUT}
  - {pin_num: M4, peripheral: UART4, signal: TX, pin_signal: ADC0_SE17/PTE24/UART4_TX/I2C0_SCL/EWM_OUT_b, direction: OUTPUT}
  - {pin_num: K5, peripheral: UART4, signal: RX, pin_signal: ADC0_SE18/PTE25/UART4_RX/I2C0_SDA/EWM_IN}
  - {pin_num: K4, peripheral: UART4, signal: CTS, pin_signal: PTE26/ENET_1588_CLKIN/UART4_CTS_b/RTC_CLKOUT/USB_CLKIN}
  - {pin_num: J4, peripheral: UART4, signal: RTS, pin_signal: PTE27/UART4_RTS_b}
  - {pin_num: H4, peripheral: GPIOE, signal: 'GPIO, 28', pin_signal: PTE28, direction: INPUT, passive_filter: enable}
  - {pin_num: H1, peripheral: USB0, signal: DP, pin_signal: USB0_DP}
  - {pin_num: H2, peripheral: USB0, signal: DM, pin_signal: USB0_DM}
  - {pin_num: J3, peripheral: ADC0, signal: 'SE, 21', pin_signal: ADC0_SE16/CMP1_IN2/ADC0_SE21}
  - {pin_num: K3, peripheral: ADC0, signal: 'SE, 22', pin_signal: ADC1_SE16/CMP2_IN2/ADC0_SE22}
  - {pin_num: L3, peripheral: ADC0, signal: 'SE, 23', pin_signal: DAC0_OUT/CMP1_IN3/ADC0_SE23}
  - {pin_num: M6, peripheral: RTC, signal: EXTAL32, pin_signal: EXTAL32}
  - {pin_num: F4, peripheral: FTM3, signal: 'CH, 2', pin_signal: PTE7/UART3_RTS_b/I2S0_RXD0/FTM3_CH2, direction: OUTPUT}
  - {pin_num: D7, peripheral: FTM3, signal: 'CH, 5', pin_signal: ADC1_SE5b/CMP0_IN3/PTC9/FTM3_CH5/I2S0_RX_BCLK/FB_AD6/FTM2_FLT0, direction: OUTPUT}
  - {pin_num: A8, peripheral: FTM3, signal: 'CH, 4', pin_signal: ADC1_SE4b/CMP0_IN2/PTC8/FTM3_CH4/I2S0_MCLK/FB_AD7, direction: OUTPUT}
  - {pin_num: C9, peripheral: GPIOD, signal: 'GPIO, 8', pin_signal: PTD8/I2C0_SCL/UART5_RX/FB_A16, direction: OUTPUT}
  - {pin_num: L8, peripheral: GPIOA, signal: 'GPIO, 9', pin_signal: PTA9/FTM1_CH1/MII0_RXD3/FTM1_QD_PHB/TRACE_D1, direction: INPUT}
  - {pin_num: G9, peripheral: GPIOB, signal: 'GPIO, 5', pin_signal: ADC1_SE11/PTB5/ENET0_1588_TMR3/FTM2_FLT0, direction: OUTPUT}
  - {pin_num: G3, peripheral: FTM3, signal: 'CH, 7', pin_signal: PTE12/I2S0_TX_BCLK/FTM3_CH7, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    /* PORTA0 (pin J5) is configured as JTAG_TCLK */
    PORT_SetPinMux(BOARD_INITPINS_SWDCLK_PORT, BOARD_INITPINS_SWDCLK_PIN, kPORT_MuxAlt7);

    /* PORTA1 (pin J6) is configured as PTA1 */
    PORT_SetPinMux(BOARD_INITPINS_AIR_WAKEN_PORT, BOARD_INITPINS_AIR_WAKEN_PIN, kPORT_MuxAsGpio);

    PORTA->PCR[1] = ((PORTA->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTA10 (pin M9) is configured as FTM2_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_MB1_PWM_PORT, BOARD_INITPINS_MB1_PWM_PIN, kPORT_MuxAlt3);

    /* PORTA11 (pin L9) is configured as FTM2_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_MB2_PWM_PORT, BOARD_INITPINS_MB2_PWM_PIN, kPORT_MuxAlt3);

    /* PORTA12 (pin K9) is configured as I2S0_TXD0 */
    PORT_SetPinMux(BOARD_INITPINS_I2S_TXD_PORT, BOARD_INITPINS_I2S_TXD_PIN, kPORT_MuxAlt6);

    /* PORTA13 (pin J9) is configured as I2C2_SDA */
    PORT_SetPinMux(BOARD_INITPINS_I2C2_SDA_PORT, BOARD_INITPINS_I2C2_SDA_PIN, kPORT_MuxAlt5);

    PORTA->PCR[13] = ((PORTA->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable)

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                       * is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTA14 (pin L10) is configured as I2C2_SCL */
    PORT_SetPinMux(BOARD_INITPINS_I2C2_SCL_PORT, BOARD_INITPINS_I2C2_SCL_PIN, kPORT_MuxAlt5);

    PORTA->PCR[14] = ((PORTA->PCR[14] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable)

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                       * is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTA15 (pin L11) is configured as I2S0_RXD0 */
    PORT_SetPinMux(BOARD_INITPINS_I2S_RXD_PORT, BOARD_INITPINS_I2S_RXD_PIN, kPORT_MuxAlt6);

    /* PORTA16 (pin K10) is configured as I2S0_RX_FS */
    PORT_SetPinMux(BOARD_INITPINS_I2S_RX_FS_PORT, BOARD_INITPINS_I2S_RX_FS_PIN, kPORT_MuxAlt6);

    /* PORTA17 (pin K11) is configured as I2S0_MCLK */
    PORT_SetPinMux(BOARD_INITPINS_I2S_MCLK_PORT, BOARD_INITPINS_I2S_MCLK_PIN, kPORT_MuxAlt6);

    /* PORTA18 (pin M12) is configured as EXTAL0 */
    PORT_SetPinMux(PORTA, 18U, kPORT_PinDisabledOrAnalog);

    /* PORTA19 (pin M11) is configured as XTAL0 */
    PORT_SetPinMux(BOARD_INITPINS_K64_XTAL_PORT, BOARD_INITPINS_K64_XTAL_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTA2 (pin K6) is configured as PTA2 */
    PORT_SetPinMux(BOARD_INITPINS_TOUCH_RST_PORT, BOARD_INITPINS_TOUCH_RST_PIN, kPORT_MuxAsGpio);

    PORTA->PCR[2] = ((PORTA->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTA24 (pin K12) is configured as PTA24 */
    PORT_SetPinMux(BOARD_INITPINS_TOUCH_TXEN_PORT, BOARD_INITPINS_TOUCH_TXEN_PIN, kPORT_MuxAsGpio);

    PORTA->PCR[24] = ((PORTA->PCR[24] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTA25 (pin J12) is configured as PTA25 */
    PORT_SetPinMux(BOARD_INITPINS_AUTH_RST_PORT, BOARD_INITPINS_AUTH_RST_PIN, kPORT_MuxAsGpio);

    /* PORTA26 (pin J11) is configured as PTA26 */
    PORT_SetPinMux(BOARD_INITPINS_MB2_RST_PORT, BOARD_INITPINS_MB2_RST_PIN, kPORT_MuxAsGpio);

    /* PORTA27 (pin J10) is configured as PTA27 */
    PORT_SetPinMux(BOARD_INITPINS_AIR_INTN_PORT, BOARD_INITPINS_AIR_INTN_PIN, kPORT_MuxAsGpio);

    /* PORTA28 (pin H12) is configured as PTA28 */
    PORT_SetPinMux(BOARD_INITPINS_NTAG_FD_PORT, BOARD_INITPINS_NTAG_FD_PIN, kPORT_MuxAsGpio);

    /* PORTA29 (pin H11) is configured as PTA29 */
    PORT_SetPinMux(BOARD_INITPINS_CHG_STATE_PORT, BOARD_INITPINS_CHG_STATE_PIN, kPORT_MuxAsGpio);

    /* PORTA3 (pin K7) is configured as JTAG_TMS */
    PORT_SetPinMux(BOARD_INITPINS_K64_SWDIO_PORT, BOARD_INITPINS_K64_SWDIO_PIN, kPORT_MuxAlt7);

    /* PORTA4 (pin L7) is configured as PTA4 */
    PORT_SetPinMux(BOARD_INITPINS_USER_SW1_PORT, BOARD_INITPINS_USER_SW1_PIN, kPORT_MuxAsGpio);

    PORTA->PCR[4] = ((PORTA->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_PFE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullUp)

                     /* Pull Enable: Internal pullup or pulldown resistor is not enabled on the corresponding pin. */
                     | PORT_PCR_PE(kPORT_PullDisable)

                     /* Passive Filter Enable: Passive input filter is enabled on the corresponding pin, if the
                      * pin is configured as a digital input. Refer to the device data sheet for filter characteristics. */
                     | PORT_PCR_PFE(kPORT_PassiveFilterEnable));

    /* PORTA5 (pin M8) is configured as I2S0_TX_BCLK */
    PORT_SetPinMux(BOARD_INITPINS_I2S_TX_BCLK_PORT, BOARD_INITPINS_I2S_TX_BCLK_PIN, kPORT_MuxAlt6);

    /* PORTA6 (pin J7) is configured as PTA6 */
    PORT_SetPinMux(BOARD_INITPINS_AIR_RESETN_PORT, BOARD_INITPINS_AIR_RESETN_PIN, kPORT_MuxAsGpio);

    PORTA->PCR[6] = ((PORTA->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_ODE(kPORT_OpenDrainEnable)

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTA7 (pin J8) is configured as PTA7 */
    PORT_SetPinMux(BOARD_INITPINS_AIR_QUALITY_EN_PORT, BOARD_INITPINS_AIR_QUALITY_EN_PIN, kPORT_MuxAsGpio);

    PORTA->PCR[7] = ((PORTA->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pulldown resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullDown));

    /* PORTA8 (pin K8) is configured as FTM1_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_BUZZER_PWM_PORT, BOARD_INITPINS_BUZZER_PWM_PIN, kPORT_MuxAlt3);

    /* PORTA9 (pin L8) is configured as PTA9 */
    PORT_SetPinMux(BOARD_INITPINS_TOUCH_INT_PORT, BOARD_INITPINS_TOUCH_INT_PIN, kPORT_MuxAsGpio);

    /* PORTB0 (pin H10) is configured as PTB0 */
    PORT_SetPinMux(BOARD_INITPINS_KW41_WAKE_UP_PORT, BOARD_INITPINS_KW41_WAKE_UP_PIN, kPORT_MuxAsGpio);

    /* PORTB1 (pin H9) is configured as FTM1_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_MB3_PWM_PORT, BOARD_INITPINS_MB3_PWM_PIN, kPORT_MuxAlt3);

    /* PORTB10 (pin E12) is configured as PTB10 */
    PORT_SetPinMux(BOARD_INITPINS_MB3_RST_PORT, BOARD_INITPINS_MB3_RST_PIN, kPORT_MuxAsGpio);

    /* PORTB11 (pin E11) is configured as PTB11 */
    PORT_SetPinMux(BOARD_INITPINS_MB1_RST_PORT, BOARD_INITPINS_MB1_RST_PIN, kPORT_MuxAsGpio);

    /* PORTB16 (pin E10) is configured as UART0_RX */
    PORT_SetPinMux(BOARD_INITPINS_UART_DBG_RX_PORT, BOARD_INITPINS_UART_DBG_RX_PIN, kPORT_MuxAlt3);

    /* PORTB17 (pin E9) is configured as UART0_TX */
    PORT_SetPinMux(BOARD_INITPINS_UART_DBG_TX_PORT, BOARD_INITPINS_UART_DBG_TX_PIN, kPORT_MuxAlt3);

    /* PORTB18 (pin D12) is configured as CAN0_TX */
    PORT_SetPinMux(BOARD_INITPINS_CAN_TX_PORT, BOARD_INITPINS_CAN_TX_PIN, kPORT_MuxAlt2);

    /* PORTB19 (pin D11) is configured as CAN0_RX */
    PORT_SetPinMux(BOARD_INITPINS_CAN_RX_PORT, BOARD_INITPINS_CAN_RX_PIN, kPORT_MuxAlt2);

    /* PORTB2 (pin G12) is configured as I2C0_SCL */
    PORT_SetPinMux(BOARD_INITPINS_I2C0_SCL_PORT, BOARD_INITPINS_I2C0_SCL_PIN, kPORT_MuxAlt2);

    PORTB->PCR[2] = ((PORTB->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_ODE(kPORT_OpenDrainEnable)

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTB23 (pin C11) is configured as PTB23 */
    PORT_SetPinMux(BOARD_INITPINS_KW41_RST_PORT, BOARD_INITPINS_KW41_RST_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[23] = ((PORTB->PCR[23] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK)))
//            (~(PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable)

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                       * is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTB3 (pin G11) is configured as I2C0_SDA */
    PORT_SetPinMux(BOARD_INITPINS_I2C0_SDA_PORT, BOARD_INITPINS_I2C0_SDA_PIN, kPORT_MuxAlt2);

    PORTB->PCR[3] = ((PORTB->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_ODE(kPORT_OpenDrainEnable)

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTB4 (pin G10) is configured as PTB4 */
    PORT_SetPinMux(BOARD_INITPINS_MB1_INT_PORT, BOARD_INITPINS_MB1_INT_PIN, kPORT_MuxAsGpio);

    /* PORTB5 (pin G9) is configured as PTB5 */
    PORT_SetPinMux(BOARD_INITPINS_NTAG_I2C_EN_PORT, BOARD_INITPINS_NTAG_I2C_EN_PIN, kPORT_MuxAsGpio);

    /* PORTB6 (pin F12) is configured as ADC1_SE12 */
    PORT_SetPinMux(BOARD_INITPINS_MB3_AN_PORT, BOARD_INITPINS_MB3_AN_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTB7 (pin F11) is configured as PTB7 */
    PORT_SetPinMux(BOARD_INITPINS_MB3_INT_PORT, BOARD_INITPINS_MB3_INT_PIN, kPORT_MuxAsGpio);

    /* PORTB8 (pin F10) is configured as PTB8 */
    PORT_SetPinMux(BOARD_INITPINS_MB2_INT_PORT, BOARD_INITPINS_MB2_INT_PIN, kPORT_MuxAsGpio);

    /* PORTB9 (pin F9) is configured as SPI1_PCS1 */
    PORT_SetPinMux(BOARD_INITPINS_SPI1_PCS1_PORT, BOARD_INITPINS_SPI1_PCS1_PIN, kPORT_MuxAlt2);

    /* PORTC0 (pin B12) is configured as PTC0 */
    PORT_SetPinMux(BOARD_INITPINS_AMB_INT_PORT, BOARD_INITPINS_AMB_INT_PIN, kPORT_MuxAsGpio);

    /* PORTC1 (pin B11) is configured as PTC1 */
    PORT_SetPinMux(BOARD_INITPINS_ACCEL_INT1_PORT, BOARD_INITPINS_ACCEL_INT1_PIN, kPORT_MuxAsGpio);

    /* PORTC10 (pin C7) is configured as I2C1_SCL */
    PORT_SetPinMux(BOARD_INITPINS_I2C1_SCL_PORT, BOARD_INITPINS_I2C1_SCL_PIN, kPORT_MuxAlt2);

    PORTC->PCR[10] = ((PORTC->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable)

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                       * is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTC11 (pin B7) is configured as I2C1_SDA */
    PORT_SetPinMux(BOARD_INITPINS_I2C1_SDA_PORT, BOARD_INITPINS_I2C1_SDA_PIN, kPORT_MuxAlt2);

    PORTC->PCR[11] = ((PORTC->PCR[11] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable)

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                       * is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTC12 (pin A7) is configured as PTC12 */
    PORT_SetPinMux(BOARD_INITPINS_NTAG_EN_PORT, BOARD_INITPINS_NTAG_EN_PIN, kPORT_MuxAsGpio);

    /* PORTC13 (pin D6) is configured as PTC13 */
    PORT_SetPinMux(BOARD_INITPINS_KW41_PB18_PORT, BOARD_INITPINS_KW41_PB18_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[13] = ((PORTC->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable)

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                       * is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTC14 (pin C6) is configured as PTC14 */
    PORT_SetPinMux(BOARD_INITPINS_BAT_SENS_EN_PORT, BOARD_INITPINS_BAT_SENS_EN_PIN, kPORT_MuxAsGpio);

    /* PORTC15 (pin B6) is configured as PTC15 */
    PORT_SetPinMux(BOARD_INITPINS_GYRO_RST_PORT, BOARD_INITPINS_GYRO_RST_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[15] = ((PORTC->PCR[15] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable)

                      /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                       * is configured as a digital output. */
                      | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTC16 (pin A6) is configured as UART3_RX */
    PORT_SetPinMux(BOARD_INITPINS_UART3_RX_PORT, BOARD_INITPINS_UART3_RX_PIN, kPORT_MuxAlt3);

    /* PORTC17 (pin D5) is configured as UART3_TX */
    PORT_SetPinMux(BOARD_INITPINS_UART3_TX_PORT, BOARD_INITPINS_UART3_TX_PIN, kPORT_MuxAlt3);

    /* PORTC18 (pin C5) is configured as PTC18 */
    PORT_SetPinMux(BOARD_INITPINS_GYRO_INT2_PORT, BOARD_INITPINS_GYRO_INT2_PIN, kPORT_MuxAsGpio);

    /* PORTC19 (pin B5) is configured as PTC19 */
    PORT_SetPinMux(BOARD_INITPINS_USB_VBUS_PORT, BOARD_INITPINS_USB_VBUS_PIN, kPORT_MuxAsGpio);

    /* PORTC2 (pin A12) is configured as SPI0_PCS2 */
    PORT_SetPinMux(BOARD_INITPINS_MB3_SPI_CS_PORT, BOARD_INITPINS_MB3_SPI_CS_PIN, kPORT_MuxAlt2);

    /* PORTC3 (pin A11) is configured as SPI0_PCS1 */
    PORT_SetPinMux(BOARD_INITPINS_MB2_SPI_CS_PORT, BOARD_INITPINS_MB2_SPI_CS_PIN, kPORT_MuxAlt2);

    /* PORTC4 (pin A9) is configured as SPI0_PCS0 */
    PORT_SetPinMux(BOARD_INITPINS_MB1_SPI_CS_PORT, BOARD_INITPINS_MB1_SPI_CS_PIN, kPORT_MuxAlt2);

    /* PORTC5 (pin D8) is configured as SPI0_SCK */
    PORT_SetPinMux(BOARD_INITPINS_MB_SPI_SCK_PORT, BOARD_INITPINS_MB_SPI_SCK_PIN, kPORT_MuxAlt2);

    /* PORTC6 (pin C8) is configured as SPI0_SOUT */
    PORT_SetPinMux(BOARD_INITPINS_MB_SPI_MOSI_PORT, BOARD_INITPINS_MB_SPI_MOSI_PIN, kPORT_MuxAlt2);

    /* PORTC7 (pin B8) is configured as SPI0_SIN */
    PORT_SetPinMux(BOARD_INITPINS_MB_SPI_MISO_PORT, BOARD_INITPINS_MB_SPI_MISO_PIN, kPORT_MuxAlt2);

    /* PORTC8 (pin A8) is configured as FTM3_CH4 */
    PORT_SetPinMux(BOARD_INITPINS_RGB_R_PORT, BOARD_INITPINS_RGB_R_PIN, kPORT_MuxAlt3);

    /* PORTC9 (pin D7) is configured as FTM3_CH5 */
    PORT_SetPinMux(BOARD_INITPINS_RGB_B_PORT, BOARD_INITPINS_RGB_B_PIN, kPORT_MuxAlt3);

    /* PORTD0 (pin A5) is configured as PTD0 */
    PORT_SetPinMux(BOARD_INITPINS_RTC_INT_PORT, BOARD_INITPINS_RTC_INT_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[0] = ((PORTD->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTD1 (pin D4) is configured as PTD1 */
    PORT_SetPinMux(BOARD_INITPINS_GYRO_INT1_PORT, BOARD_INITPINS_GYRO_INT1_PIN, kPORT_MuxAsGpio);

    /* PORTD10 (pin B3) is configured as PTD10 */
    PORT_SetPinMux(BOARD_INITPINS_PRESSURE_INT2_PORT, BOARD_INITPINS_PRESSURE_INT2_PIN, kPORT_MuxAsGpio);

    /* PORTD11 (pin B2) is configured as PTD11 */
    PORT_SetPinMux(BOARD_INITPINS_ACCEL_RST_PORT, BOARD_INITPINS_ACCEL_RST_PIN, kPORT_MuxAsGpio);

    /* PORTD12 (pin B1) is configured as PTD12 */
    PORT_SetPinMux(BOARD_INITPINS_PRESSURE_INT1_PORT, BOARD_INITPINS_PRESSURE_INT1_PIN, kPORT_MuxAsGpio);

    /* PORTD13 (pin C3) is configured as PTD13 */
    PORT_SetPinMux(BOARD_INITPINS_ACCEL_INT2_PORT, BOARD_INITPINS_ACCEL_INT2_PIN, kPORT_MuxAsGpio);

    /* PORTD14 (pin C2) is configured as PTD14 */
    PORT_SetPinMux(BOARD_INITPINS_RTC_CLKOE_PORT, BOARD_INITPINS_RTC_CLKOE_PIN, kPORT_MuxAsGpio);

    /* PORTD15 (pin C1) is configured as PTD15 */
    PORT_SetPinMux(BOARD_INITPINS_DISP_DISP_PORT, BOARD_INITPINS_DISP_DISP_PIN, kPORT_MuxAsGpio);

    /* PORTD2 (pin C4) is configured as UART2_RX */
    PORT_SetPinMux(BOARD_INITPINS_UART2_RX_PORT, BOARD_INITPINS_UART2_RX_PIN, kPORT_MuxAlt3);

    /* PORTD3 (pin B4) is configured as UART2_TX */
    PORT_SetPinMux(BOARD_INITPINS_UART2_TX_PORT, BOARD_INITPINS_UART2_TX_PIN, kPORT_MuxAlt3);

    /* PORTD4 (pin A4) is configured as SPI1_PCS0 */
    PORT_SetPinMux(BOARD_INITPINS_SPI1_PCS0_PORT, BOARD_INITPINS_SPI1_PCS0_PIN, kPORT_MuxAlt7);

    PORTD->PCR[4] = ((PORTD->PCR[4] &
                      /* Mask bits to zero which are setting */
//                      (~(PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))
                      (~(PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK)))

                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_ODE(kPORT_OpenDrainEnable)

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTD5 (pin A3) is configured as SPI1_SCK */
    PORT_SetPinMux(BOARD_INITPINS_SPI1_SCK_PORT, BOARD_INITPINS_SPI1_SCK_PIN, kPORT_MuxAlt7);

    /* PORTD6 (pin A2) is configured as SPI1_SOUT */
    PORT_SetPinMux(BOARD_INITPINS_SPI1_MOSI_PORT, BOARD_INITPINS_SPI1_MOSI_PIN, kPORT_MuxAlt7);

    /* PORTD7 (pin A1) is configured as SPI1_SIN */
    PORT_SetPinMux(BOARD_INITPINS_SPI1_MISO_PORT, BOARD_INITPINS_SPI1_MISO_PIN, kPORT_MuxAlt7);

    PORTD->PCR[7] = ((PORTD->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: Low drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_LowDriveStrength));

    /* PORTD8 (pin C9) is configured as PTD8 */
    PORT_SetPinMux(BOARD_INITPINS_AIR_QUALITY_I2C_EN_PORT, BOARD_INITPINS_AIR_QUALITY_I2C_EN_PIN, kPORT_MuxAsGpio);

    /* PORTD9 (pin B9) is configured as PTD9 */
    PORT_SetPinMux(BOARD_INITPINS_DISP_EN_PORT, BOARD_INITPINS_DISP_EN_PIN, kPORT_MuxAsGpio);

    /* PORTE0 (pin D3) is configured as SDHC0_D1 */
    PORT_SetPinMux(BOARD_INITPINS_SD_D1_PORT, BOARD_INITPINS_SD_D1_PIN, kPORT_MuxAlt4);

    /* PORTE1 (pin D2) is configured as SDHC0_D0 */
    PORT_SetPinMux(BOARD_INITPINS_SD_D0_PORT, BOARD_INITPINS_SD_D0_PIN, kPORT_MuxAlt4);

    /* PORTE10 (pin F1) is configured as PTE10 */
    PORT_SetPinMux(BOARD_INITPINS_USER_SW3_PORT, BOARD_INITPINS_USER_SW3_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[10] = ((PORTE->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PFE_MASK | PORT_PCR_ISF_MASK)))

                      /* Passive Filter Enable: Passive input filter is enabled on the corresponding pin, if the
                       * pin is configured as a digital input. Refer to the device data sheet for filter characteristics. */
                      | PORT_PCR_PFE(kPORT_PassiveFilterEnable));

    /* PORTE11 (pin G4) is configured as PTE11 */
    PORT_SetPinMux(BOARD_INITPINS_DISP_EXTMODE_PORT, BOARD_INITPINS_DISP_EXTMODE_PIN, kPORT_MuxAsGpio);

    /* PORTE12 (pin G3) is configured as FTM3_CH7 */
    PORT_SetPinMux(BOARD_INITPINS_DISP_BLIGHT_PORT, BOARD_INITPINS_DISP_BLIGHT_PIN, kPORT_MuxAlt6);

    /* PORTE2 (pin D1) is configured as SDHC0_DCLK */
    PORT_SetPinMux(BOARD_INITPINS_SD_CLK_PORT, BOARD_INITPINS_SD_CLK_PIN, kPORT_MuxAlt4);

    /* PORTE24 (pin M4) is configured as UART4_TX */
    PORT_SetPinMux(BOARD_INITPINS_KW41_UART_RX_PORT, BOARD_INITPINS_KW41_UART_RX_PIN, kPORT_MuxAlt3);

    /* PORTE25 (pin K5) is configured as UART4_RX */
    PORT_SetPinMux(BOARD_INITPINS_KW41_UART_TX_PORT, BOARD_INITPINS_KW41_UART_TX_PIN, kPORT_MuxAlt3);

    /* PORTE26 (pin K4) is configured as UART4_CTS_b */
    PORT_SetPinMux(BOARD_INITPINS_KW41_UART_RTS_PORT, BOARD_INITPINS_KW41_UART_RTS_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[26] = ((PORTE->PCR[26] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_PFE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullDown)

                     /* Pull Enable: Internal pullup or pulldown resistor is not enabled on the corresponding pin. */
//                     | PORT_PCR_PE(kPORT_PullEnable)

                     /* Passive Filter Enable: Passive input filter is enabled on the corresponding pin, if the
                      * pin is configured as a digital input. Refer to the device data sheet for filter characteristics. */
                     | PORT_PCR_PFE(kPORT_PassiveFilterEnable)

					 | PORT_PCR_ISF(kPORT_InterruptRisingEdge)


    );

    /* PORTE27 (pin J4) is configured as UART4_RTS_b */
    PORT_SetPinMux(BOARD_INITPINS_KW41_UART_CTS_PORT, BOARD_INITPINS_KW41_UART_CTS_PIN, kPORT_MuxAsGpio);

    /* PORTE28 (pin H4) is configured as PTE28 */
    PORT_SetPinMux(BOARD_INITPINS_USER_SW4_PORT, BOARD_INITPINS_USER_SW4_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[28] = ((PORTE->PCR[28] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PFE_MASK | PORT_PCR_ISF_MASK)))

                      /* Passive Filter Enable: Passive input filter is enabled on the corresponding pin, if the
                       * pin is configured as a digital input. Refer to the device data sheet for filter characteristics. */
                      | PORT_PCR_PFE(kPORT_PassiveFilterEnable));

    /* PORTE3 (pin E4) is configured as SDHC0_CMD */
    PORT_SetPinMux(BOARD_INITPINS_SD_CMD_PORT, BOARD_INITPINS_SD_CMD_PIN, kPORT_MuxAlt4);

    /* PORTE4 (pin E3) is configured as SDHC0_D3 */
    PORT_SetPinMux(BOARD_INITPINS_SD_D3_PORT, BOARD_INITPINS_SD_D3_PIN, kPORT_MuxAlt4);

    /* PORTE5 (pin E2) is configured as SDHC0_D2 */
    PORT_SetPinMux(BOARD_INITPINS_SD_D2_PORT, BOARD_INITPINS_SD_D2_PIN, kPORT_MuxAlt4);

    /* PORTE6 (pin E1) is configured as FTM3_CH1 */
    PORT_SetPinMux(PORTE, 6U, kPORT_MuxAlt6);

    /* PORTE7 (pin F4) is configured as FTM3_CH2 */
    PORT_SetPinMux(BOARD_INITPINS_RGB_G_PORT, BOARD_INITPINS_RGB_G_PIN, kPORT_MuxAlt6);

    /* PORTE9 (pin F2) is configured as PTE9 */
    PORT_SetPinMux(BOARD_INITPINS_USER_SW2_PORT, BOARD_INITPINS_USER_SW2_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[9] = ((PORTE->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PFE_MASK | PORT_PCR_ISF_MASK)))

                     /* Passive Filter Enable: Passive input filter is enabled on the corresponding pin, if the
                      * pin is configured as a digital input. Refer to the device data sheet for filter characteristics. */
                     | PORT_PCR_PFE(kPORT_PassiveFilterEnable));

    SIM->SOPT4 = ((SIM->SOPT4 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT4_FTM1CH0SRC_MASK | SIM_SOPT4_FTM2CH0SRC_MASK)))

                  /* FTM1 channel 0 input capture source select: FTM1_CH0 signal. */
                  | SIM_SOPT4_FTM1CH0SRC(SOPT4_FTM1CH0SRC_FTM)

                  /* FTM2 channel 0 input capture source select: FTM2_CH0 signal. */
                  | SIM_SOPT4_FTM2CH0SRC(SOPT4_FTM2CH0SRC_FTM));

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART0TXSRC_MASK)))

                  /* UART 0 transmit data source select: UART0_TX pin. */
                  | SIM_SOPT5_UART0TXSRC(SOPT5_UART0TXSRC_UART_TX));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTC_INT_IRQ:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: A5, peripheral: GPIOD, signal: 'GPIO, 0', pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b, direction: INPUT, slew_rate: fast,
    open_drain: no_init, pull_select: up, pull_enable: enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTC_INT_IRQ
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTC_INT_IRQ(void)
{
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);

    /* PORTD0 (pin A5) is configured as PTD0 */
    PORT_SetPinMux(RTC_INT_IRQ_RTC_INT_PORT, RTC_INT_IRQ_RTC_INT_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[0] = ((PORTD->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_SRE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp)

                     /* Slew Rate Enable: Fast slew rate is configured on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_SRE(kPORT_FastSlewRate));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
DSPI2_InitPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: D9, peripheral: SPI2, signal: SCK, pin_signal: PTB21/SPI2_SCK/FB_AD30/CMP1_OUT}
  - {pin_num: C12, peripheral: SPI2, signal: SOUT, pin_signal: PTB22/SPI2_SOUT/FB_AD29/CMP2_OUT}
  - {pin_num: D10, peripheral: GPIOB, signal: 'GPIO, 20', pin_signal: PTB20/SPI2_PCS0/FB_AD31/CMP0_OUT, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : DSPI2_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void DSPI2_InitPins(void)
{
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);

    /* PORTB20 (pin D10) is configured as PTB20 */
    PORT_SetPinMux(DSPI2_INITPINS_DISP_SPI_CS_PORT, DSPI2_INITPINS_DISP_SPI_CS_PIN, kPORT_MuxAsGpio);

    /* PORTB21 (pin D9) is configured as SPI2_SCK */
    PORT_SetPinMux(DSPI2_INITPINS_DISP_SPI_SCK_PORT, DSPI2_INITPINS_DISP_SPI_SCK_PIN, kPORT_MuxAlt2);

    /* PORTB22 (pin C12) is configured as SPI2_SOUT */
    PORT_SetPinMux(DSPI2_INITPINS_DISP_SPI_SDI_PORT, DSPI2_INITPINS_DISP_SPI_SDI_PIN, kPORT_MuxAlt2);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
DSPI2_DeinitPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: D9, peripheral: n/a, signal: disabled, pin_signal: PTB21/SPI2_SCK/FB_AD30/CMP1_OUT}
  - {pin_num: D10, peripheral: n/a, signal: disabled, pin_signal: PTB20/SPI2_PCS0/FB_AD31/CMP0_OUT}
  - {pin_num: C12, peripheral: n/a, signal: disabled, pin_signal: PTB22/SPI2_SOUT/FB_AD29/CMP2_OUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : DSPI2_DeinitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void DSPI2_DeinitPins(void)
{
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);

    /* PORTB20 (pin D10) is disabled */
    PORT_SetPinMux(DSPI2_DEINITPINS_DISP_SPI_CS_PORT, DSPI2_DEINITPINS_DISP_SPI_CS_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTB21 (pin D9) is disabled */
    PORT_SetPinMux(DSPI2_DEINITPINS_DISP_SPI_SCK_PORT, DSPI2_DEINITPINS_DISP_SPI_SCK_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTB22 (pin C12) is disabled */
    PORT_SetPinMux(DSPI2_DEINITPINS_DISP_SPI_SDI_PORT, DSPI2_DEINITPINS_DISP_SPI_SDI_PIN, kPORT_PinDisabledOrAnalog);
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
